name: Fetch website data

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_ACCESS_TOKEN }}

      - name: Fetch latest data
        run: |-
          bash ./fetch-data.sh

      - name: Commit and push if data has changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(TZ='Europe/Berlin' date '+%d.%m.%Y %H:%M')
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
