name: Fetch website data

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    env:
      PUSHOVER_USER_KEY: ${{ secrets.PUSHOVER_USER_KEY }}
      PUSHOVER_APP_TOKEN: ${{ secrets.PUSHOVER_APP_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_ACCESS_TOKEN }}

      - name: Install pup
        run: |
          wget https://github.com/ericchiang/pup/releases/download/v0.4.0/pup_v0.4.0_linux_amd64.zip
          unzip pup_v0.4.0_linux_amd64.zip
          rm pup_v0.4.0_linux_amd64.zip
          sudo mv pup /usr/local/bin/

      - name: Fetch latest data
        run: |-
          bash ./fetch-data.sh

      - name: Commit and push if data has changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(TZ='Europe/Berlin' date '+%d.%m.%Y %H:%M')
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
